# Generated by Django 5.1.1 on 2024-11-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
